services:

  postgres:
    build: ./postgresql_docker
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: application
    ports:
      - "5431:5432"
    command: >
      postgres
      -c log_connections=on
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - webnet

  aspnet:
    build:
      context: .
      dockerfile: ./aspnet_docker/Dockerfile
    container_name: aspnet
    restart: unless-stopped
    expose:
      - "8080"
      - "8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - webnet


volumes:
  postgres_data:

networks:
  webnet:
    driver: bridge
